---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: southeastasia
        tags:
          testing: testing
      register: result
    - debug:
        var: result
