---
- hosts: localhost
  connection: local
  tasks:
  - command: 'echo $ALICLOUD_SECRET_KEY'
    register: result
  - debug:
      var: result.stdout
  - debug:
      msg: "{{ lookup('env','ALICLOUD_SECRET_KEY') }}"
